### ISSUE TITLE
ошибка при компиляции - error: control reaches end of non-void function [-Werror=return-type]

### ISSUE THREAD

**Issue by DiminatorDK** [MoonFox2006/MCP23017_Buttons#1]
При попытке компиляции получаю ошибку:
.pio\libdeps\d1_mini\MCP23017_Buttons\src\MCP23017.cpp: In member function 'bool MCP23017::digitalRead(uint8_t)':
.pio\libdeps\d1_mini\MCP23017_Buttons\src\MCP23017.cpp:83:1: error: control reaches end of non-void function [-Werror=return-type]
   83 | }
      | ^

Код:
bool MCP23017::digitalRead(uint8_t pin) {
  if (pin < 16) {
    return ((readReg(pin < 8 ? MCP23017_GPIOA : MCP23017_GPIOB) >> (pin % 8)) & 0x01);
  }
}

**Comment by MoonFox2006** [comment]
Fixed
